openapi: 3.0.1
info:
  title: Basic Calculator
  description: Arithmetics is just a call away!
  version: v1
servers:
  - url: http://apim-dev-2023.azure-api.net/calcapi/v1
paths:
  /add:
    get:
      summary: Add two integers
      description: Produces a sum of two numbers.
      operationId: 64c02715217d20198c4971fa
      parameters:
        - name: a
          in: query
          description: First operand. Default value is <code>51</code>.
          required: true
          schema:
            enum:
              - ''
            type: string
        - name: b
          in: query
          description: Second operand. Default value is <code>49</code>.
          required: true
          schema:
            enum:
              - ''
            type: string
      responses:
        '200':
          description: ''
  /sub:
    get:
      summary: Subtract two integers
      description: Produces a difference between two numbers.
      operationId: 64c02715217d20198c4971fb
      parameters:
        - name: a
          in: query
          description: First operand. Default value is <code>51</code>.
          required: true
          schema:
            enum:
              - ''
            type: string
        - name: b
          in: query
          description: Second operand. Default value is <code>49</code>.
          required: true
          schema:
            enum:
              - ''
            type: string
      responses:
        '200':
          description: ''
  /mul:
    get:
      summary: Multiply two integers
      description: Produces a product of two numbers.
      operationId: 64c02715217d20198c4971fc
      parameters:
        - name: a
          in: query
          description: First operand. Default value is <code>51</code>.
          required: true
          schema:
            enum:
              - ''
            type: string
        - name: b
          in: query
          description: Second operand. Default value is <code>49</code>.
          required: true
          schema:
            enum:
              - ''
            type: string
      responses:
        '200':
          description: ''
  /div:
    get:
      summary: Divide two integers
      description: Produces a quotient of two numbers.
      operationId: 64c02715217d20198c4971fd
      parameters:
        - name: a
          in: query
          description: First operand. Default value is <code>51</code>.
          required: true
          schema:
            enum:
              - ''
            type: string
        - name: b
          in: query
          description: Second operand. Default value is <code>49</code>.
          required: true
          schema:
            enum:
              - ''
            type: string
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]